name: My Workflow

on:
  pull_request:
  push:

jobs:
  my_job:
    name: My Job on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
      - run: ./test.sh
